(function(){var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),q=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&n(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,h){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}});return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},fa=function(a){return ea(a,a)},ea=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},ha=function(){for(var a=
Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};q("globalThis",function(a){return a||ca});q("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});
q("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function d(k){if(!t(k,f)){var l=new b;n(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(p){if(p instanceof b)return p;Object.isExtensible(p)&&d(p);return l(p)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),p=new a([[k,2],[l,3]]);if(p.get(k)!=2||p.get(l)!=3)return!1;p.delete(k);p.set(l,4);return!p.has(k)&&p.get(l)==4}catch(E){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};g.prototype.get=function(k){return c(k)&&t(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)};
g.prototype.delete=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)?delete k[f][this.g]:!1};return g});
q("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(r([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),p=l.next();if(p.done||p.value[0]!=g||p.value[1]!="s")return!1;p=l.next();return p.done||p.value[0].x!=4||p.value[1]!="t"||!l.next().done?!1:!0}catch(E){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=
f();this.size=0;if(g){g=r(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],G:this[1].G,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].G.next=l.entry,this[1].G=l.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.G.next=
g.entry.next,g.entry.next.G=g.entry.G,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].G=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=
function(g,k){for(var l=this.entries(),p;!(p=l.next()).done;)p=p.value,g.call(k,p[1],p[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var l=k&&typeof k;l=="object"||l=="function"?b.has(k)?l=b.get(k):(l=""+ ++h,b.set(k,l)):l="p_"+k;var p=g[0][l];if(p&&t(g[0],l))for(g=0;g<p.length;g++){var E=p[g];if(k!==k&&E.key!==E.key||k===E.key)return{id:l,list:p,index:g,entry:E}}return{id:l,list:p,index:-1,entry:void 0}},e=function(g,k){var l=g[1];return da(function(){if(l){for(;l.head!=
g[1];)l=l.G;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.G=g.next=g.head=g},h=0;return c});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push(b[d]);return c}});
q("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});
var ia=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(b){return b})}});q("Array.prototype.values",function(a){return a?a:function(){return ia(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ja=ja||{},u=this||self,ka=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},v=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},la=function(a,b,c){return a.call.apply(a.bind,arguments)},ma=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,
d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?la:ma;return w.apply(null,arguments)},x=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Xa=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}};var na=function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},oa=function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},pa=function(a,b){for(var c=a.length,d=Array(c),e=typeof a==="string"?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},qa=function(a,b){var c=-1;oa(a,function(d,e){c=b.call(void 0,c,d,e,a)});
return c};function ra(a,b){b=na(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function sa(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function ta(a){for(var b=[],c=0;c<a;c++)b[c]="";return b};var ua=function(a){ua[" "](a);return a};ua[" "]=function(){};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var va=globalThis.trustedTypes,wa;function xa(){var a=null;if(!va)return a;try{var b=function(c){return c};a=va.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function ya(){wa===void 0&&(wa=xa());return wa};var za=function(a){this.g=a};za.prototype.toString=function(){return this.g+""};function Aa(a){var b=ya();a=b?b.createScriptURL(a):a;return new za(a)};var Ba=function(a){this.g=a};Ba.prototype.toString=function(){return this.g+""};function Ca(a){var b=ya();a=b?b.createHTML(a):a;return new Ba(a)}function Da(a){if(a instanceof Ba)return a.g;throw Error("");};var Fa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=u.document.createElement("div");return a.replace(Ea,function(d,e){var f=b[d];if(f)return f;e.charAt(0)=="#"&&(e=Number("0"+e.slice(1)),isNaN(e)||(f=String.fromCharCode(e)));if(!f){f=Ca(d+" ");if(c.nodeType===1&&/^(script|style)$/i.test(c.tagName))throw Error("");c.innerHTML=Da(f);f=c.firstChild.nodeValue.slice(0,-1)}return b[d]=f})},Ga=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";
case "lt":return"<";case "gt":return">";case "quot":return'"';default:return c.charAt(0)!="#"||(c=Number("0"+c.slice(1)),isNaN(c))?b:String.fromCharCode(c)}})},Ea=/&([^;\s<&]+);?/g;function Ha(a){var b,c;return(c=(b=/https?:\/\/[^\/]+/.exec(a))==null?void 0:b[0])!=null?c:""};function Ia(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};var Ja=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};u.addEventListener("test",c,b);u.removeEventListener("test",c,b)}catch(d){}return a}();function Ka(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var La="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ma(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<La.length;f++)c=La[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Oa=function(a,b){Ka(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Na.hasOwnProperty(d)?a.setAttribute(Na[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})},Na={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Qa=function(a,
b,c){var d=arguments,e=document,f=d[1];var h=String(d[0]);h=String(h);e.contentType==="application/xhtml+xml"&&(h=h.toLowerCase());h=e.createElement(h);f&&(typeof f==="string"?h.className=f:Array.isArray(f)?h.className=f.join(" "):Oa(h,f));d.length>2&&Pa(e,h,d);return h},Pa=function(a,b,c){function d(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var e=2;e<c.length;e++){var f=c[e];if(!ka(f)||v(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(v(f)){var h=typeof f.item==
"function"||typeof f.item=="string";break a}if(typeof f==="function"){h=typeof f.item=="function";break a}}h=!1}oa(h?sa(f):f,d)}}},y=function(a){return a.nodeType==9?a:a.ownerDocument||a.document};function Ra(a,b){if(typeof ReportingObserver==="undefined")return null;var c=function(e){e=r(e);for(var f=e.next();!f.done;f=e.next())f=f.value,a(f)&&b(f)},d=new ReportingObserver(c,{buffered:!0});u.addEventListener("pagehide",function(){c(d.takeRecords(),d);d.disconnect()});d.observe();return d};var Sa={xa:"AdClickThru",ya:"AdDurationChange",AD_ERROR:"AdError",za:"AdExpandedChange",Aa:"AdImpression",Ba:"AdInteraction",Ca:"AdLinearChange",Da:"AdLoaded",Ea:"AdLog",Fa:"AdPaused",Ga:"AdPlaying",Ha:"AdRemainingTimeChange",Ia:"AdSizeChange",Ka:"AdSkipped",La:"AdStarted",Ma:"AdStopped",Ja:"AdSkippableStateChange",Na:"AdUserAcceptInvitation",Oa:"AdUserClose",Pa:"AdUserMinimize",Qa:"AdVideoComplete",Ra:"AdVideoFirstQuartile",Sa:"AdVideoMidpoint",Ta:"AdVideoStart",Ua:"AdVideoThirdQuartile",Va:"AdVolumeChange",
Wa:"Ping"};var Ta=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)"),Xa=function(a){a=a||Ua();for(var b=new Va(u.location.href,!1),c=null,d=a.length-1,e=d;e>=0;--e){var f=a[e];!c&&Ta.test(f.url)&&(c=f);if(f.url&&!f.g){b=f;break}}e=null;f=a.length&&a[d].url;b.depth!==0&&f&&(e=a[d]);return new Wa(b,e,c)},Ua=function(){var a=u,b=[],c=null;do{var d=a;try{var e;if(e=!!d&&d.location.href!=null)b:{try{ua(d.foo);e=!0;break b}catch(g){}e=!1}var f=e}catch(g){f=!1}if(f){var h=d.location.href;c=d.document&&
d.document.referrer||null}else h=c,c=null;b.push(new Va(h||""));try{a=d.parent}catch(g){a=null}}while(a&&d!==a);d=0;for(a=b.length-1;d<=a;++d)b[d].depth=a-d;d=u;if(d.location&&d.location.ancestorOrigins&&d.location.ancestorOrigins.length===b.length-1)for(a=1;a<b.length;++a)h=b[a],h.url||(h.url=d.location.ancestorOrigins[a-1]||"",h.g=!0);return b},Wa=function(a,b,c){this.i=a;this.j=b;this.g=c},Va=function(a,b){this.url=a;this.g=!!b;this.depth=null};var Za=function(a,b,c,d,e){var f=[];Ia(a,function(h,g){(h=Ya(h,b,c,d,e))&&f.push(g+"="+h)});return f.join(b)},Ya=function(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";typeof c==="string"&&(c=c.split(""));if(a instanceof Array){if(d||(d=0),d<c.length){for(var f=[],h=0;h<a.length;h++)f.push(Ya(a[h],b,c,d+1,e));return f.join(c[d])}}else if(typeof a==="object")return e||(e=0),e<2?encodeURIComponent(Za(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))};var z=function(a,b){this.g=a;this.depth=b},ab=function(){var a=Ua(),b=Math.max(a.length-1,0),c=Xa(a);a=c.i;var d=c.j,e=c.g,f=[];c=function(g,k){return g==null?k:g};e&&f.push(new z([e.url,e.g?2:0],c(e.depth,1)));d&&d!=e&&f.push(new z([d.url,2],0));a.url&&a!=e&&f.push(new z([a.url,0],c(a.depth,b)));var h=pa(f,function(g,k){return f.slice(0,f.length-k)});!a.url||(e||d)&&a!=e||(d=Ha(a.url))&&h.push([new z([d,1],c(a.depth,b))]);h.push([]);return pa(h,function(g){return $a(b,g)})};
function $a(a,b){var c=qa(b,function(e,f){return Math.max(e,f.depth)}),d=ta(c+2);d[0]=a;oa(b,function(e){return d[e.depth+1]=e.g});return d}function bb(){var a=a===void 0?ab():a;return a.map(function(b){return Ya(b)})};var cb=function(a){if(typeof DOMParser!="undefined"){var b=new DOMParser;a=Ca(a===null?"null":a===void 0?"undefined":a);return b.parseFromString(Da(a),"application/xml")}throw Error("Your browser does not support loading xml documents");};var db=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var A=function(){this.o=this.o;this.v=this.v};A.prototype.o=!1;A.prototype.dispose=function(){this.o||(this.o=!0,this.m())};A.prototype[Symbol.dispose]=function(){this.dispose()};A.prototype.m=function(){if(this.v)for(;this.v.length;)this.v.shift()()};var B=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=!1};B.prototype.preventDefault=function(){this.defaultPrevented=!0};var C=function(a,b){B.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.g=null;a&&this.init(a,b)};x(C,B);
C.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=
a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.g=a;a.defaultPrevented&&C.R.preventDefault.call(this)};
C.prototype.preventDefault=function(){C.R.preventDefault.call(this);var a=this.g;a.preventDefault?a.preventDefault():a.returnValue=!1};var D="closure_listenable_"+(Math.random()*1E6|0);var eb=0;var fb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.handler=e;this.key=++eb;this.M=this.P=!1},F=function(a){a.M=!0;a.listener=null;a.proxy=null;a.src=null;a.handler=null};function G(a){this.src=a;this.g={};this.i=0}G.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.i++);var h=gb(a,b,d,e);h>-1?(b=a[h],c||(b.P=!1)):(b=new fb(b,this.src,f,!!d,e),b.P=c,a.push(b));return b};var hb=function(a,b){var c=b.type;c in a.g&&ra(a.g[c],b)&&(F(b),a.g[c].length==0&&(delete a.g[c],a.i--))},gb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.M&&f.listener==b&&f.capture==!!c&&f.handler==d)return e}return-1};var ib="closure_lm_"+(Math.random()*1E6|0),jb={},kb=0,mb=function(a,b,c,d,e){if(d&&d.once)lb(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)mb(a,b[f],c,d,e);else c=nb(c),a&&a[D]?a.listen(b,c,v(d)?!!d.capture:!!d,e):ob(a,b,c,!1,d,e)},ob=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,g=pb(a);g||(a[ib]=g=new G(a));c=g.add(b,c,d,h,f);if(!c.proxy){d=qb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Ja||(e=h),e===void 0&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(rb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");kb++}},qb=function(){var a=sb,b=function(c){return a.call(b.src,b.listener,c)};return b},lb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)lb(a,b[f],c,d,e);else c=nb(c),a&&a[D]?a.g.add(String(b),c,!0,v(d)?!!d.capture:!!d,e):ob(a,b,c,!0,d,e)},tb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=
0;f<b.length;f++)tb(a,b[f],c,d,e);else(d=v(d)?!!d.capture:!!d,c=nb(c),a&&a[D])?(a=a.g,b=String(b).toString(),b in a.g&&(f=a.g[b],c=gb(f,c,d,e),c>-1&&(F(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.i--)))):a&&(a=pb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=gb(b,c,d,e)),(c=a>-1?b[a]:null)&&ub(c))},ub=function(a){if(typeof a!=="number"&&a&&!a.M){var b=a.src;if(b&&b[D])hb(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(rb(c),
d):b.addListener&&b.removeListener&&b.removeListener(d);kb--;(c=pb(b))?(hb(c,a),c.i==0&&(c.src=null,b[ib]=null)):F(a)}}},rb=function(a){return a in jb?jb[a]:jb[a]="on"+a},sb=function(a,b){if(a.M)a=!0;else{b=new C(b,this);var c=a.listener,d=a.handler||a.src;a.P&&ub(a);a=c.call(d,b)}return a},pb=function(a){a=a[ib];return a instanceof G?a:null},vb="__closure_events_fn_"+(Math.random()*1E9>>>0),nb=function(a){if(typeof a==="function")return a;a[vb]||(a[vb]=function(b){return a.handleEvent(b)});return a[vb]};var H=function(){A.call(this);this.g=new G(this);this.L=this;this.F=null};x(H,A);H.prototype[D]=!0;H.prototype.addEventListener=function(a,b,c,d){mb(this,a,b,c,d)};H.prototype.removeEventListener=function(a,b,c,d){tb(this,a,b,c,d)};
var J=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.L;d=b.type||b;if(typeof b==="string")b=new B(b,a);else if(b instanceof B)b.target=b.target||a;else{var e=b;b=new B(d,a);Ma(b,e)}e=!0;var f;if(c)for(f=c.length-1;f>=0;f--){var h=b.currentTarget=c[f];e=I(h,d,!0,b)&&e}h=b.currentTarget=a;e=I(h,d,!0,b)&&e;e=I(h,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)h=b.currentTarget=c[f],e=I(h,d,!1,b)&&e};
H.prototype.m=function(){H.R.m.call(this);if(this.g){var a=this.g,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,F(d[e]);delete a.g[c];a.i--}}this.F=null};H.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};var I=function(a,b,c,d){b=a.g.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.M&&h.capture==c){var g=h.listener,k=h.handler||h.src;h.P&&hb(a.g,h);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};var wb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),xb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var K=function(){H.call(this);this.headers=new Map;this.i=!1;this.l=null;this.D="";this.j=this.C=this.u=this.A=!1;this.H=null;this.J="";this.K=!1};x(K,H);var yb=/^https?$/i,zb=["POST","PUT"],Ab=[],Cb=function(a,b){var c=new K;Ab.push(c);b&&c.listen("complete",b);c.g.add("ready",c.N,!0,void 0,void 0);Bb(c,a)};K.prototype.N=function(){this.dispose();ra(Ab,this)};
var Bb=function(a,b){if(a.l)throw Error("[goog.net.XhrIo] Object is active with another request="+a.D+"; newUri="+b);a.D=b;a.A=!1;a.i=!0;a.l=new XMLHttpRequest;a.l.onreadystatechange=db(w(a.I,a));try{a.C=!0,a.l.open("GET",String(b),!0),a.C=!1}catch(e){Db(a);return}b=new Map(a.headers);var c=Array.from(b.keys()).find(function(e){return"content-type"==e.toLowerCase()}),d=u.FormData&&!1;!(na(zb,"GET")>=0)||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=r(b);for(c=b.next();!c.done;c=
b.next())d=r(c.value),c=d.next().value,d=d.next().value,a.l.setRequestHeader(c,d);a.J&&(a.l.responseType=a.J);"withCredentials"in a.l&&a.l.withCredentials!==a.K&&(a.l.withCredentials=a.K);try{Eb(a),a.u=!0,a.l.send(""),a.u=!1}catch(e){Db(a)}},Db=function(a){a.i=!1;a.l&&(a.j=!0,a.l.abort(),a.j=!1);Fb(a);L(a)},Fb=function(a){a.A||(a.A=!0,J(a,"complete"),J(a,"error"))};K.prototype.abort=function(){this.l&&this.i&&(this.i=!1,this.j=!0,this.l.abort(),this.j=!1,J(this,"complete"),J(this,"abort"),L(this))};
K.prototype.m=function(){this.l&&(this.i&&(this.i=!1,this.j=!0,this.l.abort(),this.j=!1),L(this,!0));K.R.m.call(this)};K.prototype.I=function(){this.o||(this.C||this.u||this.j?Gb(this):this.O())};K.prototype.O=function(){Gb(this)};
var Gb=function(a){if(a.i&&typeof ja!="undefined")if(a.u&&(a.l?a.l.readyState:0)==4)setTimeout(a.I.bind(a),0);else if(J(a,"readystatechange"),(a.l?a.l.readyState:0)==4){a.i=!1;try{Hb(a)?(J(a,"complete"),J(a,"success")):Fb(a)}finally{L(a)}}},L=function(a,b){if(a.l){Eb(a);var c=a.l;a.l=null;b||J(a,"ready");try{c.onreadystatechange=null}catch(d){}}},Eb=function(a){a.H&&(clearTimeout(a.H),a.H=null)};K.prototype.isActive=function(){return!!this.l};
var Hb=function(a){var b=Ib(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=b===0)a=String(a.D).match(wb)[1]||null,!a&&u.self&&u.self.location&&(a=u.self.location.protocol.slice(0,-1)),b=!yb.test(a?a.toLowerCase():"");c=b}return c},Ib=function(a){try{return(a.l?a.l.readyState:0)>2?a.l.status:-1}catch(b){return-1}};var Jb=/^https?:\/\/ad.doubleclick.net\//,Kb=/;dc_qid=([^;]+)/,Lb=function(){this.statusText="";this.error=!1;this.g=0},Nb=function(a,b,c){if(b=Mb(b))a.i=c,a.g=1,Cb(b,function(d){a.g=0;d=d.target;if(Hb(d)){try{var e=d.l?d.l.responseText:""}catch(g){e=""}if((e=cb(e))&&e.documentElement&&e.getElementsByTagName("parsererror").length===0){if(typeof e.selectNodes!="undefined"){var f=y(e);typeof f.setProperty!="undefined"&&f.setProperty("SelectionLanguage","XPath");e=e.selectNodes("/VAST/Ad")}else if(document.implementation.hasFeature("XPath",
"3.0")){f=y(e);d=f.createNSResolver(f.documentElement);e=f.evaluate("/VAST/Ad",e,d,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);f=[];d=e.snapshotLength;for(var h=0;h<d;h++)f.push(e.snapshotItem(h));e=f}else e=[];e.length===0&&(a.g=2)}else a.statusText="XML error",a.error=!0}else{if(d==null)f=void 0;else try{f=(d.l?d.l.readyState:0)>2?d.l.statusText:""}catch(g){f=""}a.statusText=(d==null?void 0:Ib(d))+" "+f;a.error=!0}a.i&&a.i()})},Mb=function(a){try{if(!a)return null;var b=cb(a),c,d;if(typeof b.selectSingleNode!=
"undefined"){var e=y(b);typeof e.setProperty!="undefined"&&e.setProperty("SelectionLanguage","XPath");var f=b.selectSingleNode("/VAST/Ad/*/Extensions/Extension[@type='DCMOriginalRequest']/RequestUrl")}else if(document.implementation.hasFeature("XPath","3.0")){var h=y(b),g=h.createNSResolver(h.documentElement);f=h.evaluate("/VAST/Ad/*/Extensions/Extension[@type='DCMOriginalRequest']/RequestUrl",b,g,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}else f=null;var k=(c=f)==null?void 0:(d=c.firstChild)==
null?void 0:d.nodeValue;if(!k||!Jb.test(k))return null;Kb.exec(k);return k+";dc_rfl="+bb()[0]}catch(l){return null}};var M=function(a,b){this.j=this.v=this.m="";this.A=null;this.u=this.i="";this.o=!1;var c;a instanceof M?(this.o=b!==void 0?b:a.o,Ob(this,a.m),this.v=a.v,this.j=a.j,Pb(this,a.A),this.i=a.i,Qb(this,Rb(a.g)),this.u=a.u):a&&(c=String(a).match(wb))?(this.o=!!b,Ob(this,c[1]||"",!0),this.v=N(c[2]||""),this.j=N(c[3]||"",!0),Pb(this,c[4]),this.i=N(c[5]||"",!0),Qb(this,c[6]||"",!0),this.u=N(c[7]||"")):(this.o=!!b,this.g=new O(null,this.o))};
M.prototype.toString=function(){var a=[],b=this.m;b&&a.push(P(b,Sb,!0),":");var c=this.j;if(c||b=="file")a.push("//"),(b=this.v)&&a.push(P(b,Sb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.A,c!=null&&a.push(":",String(c));if(c=this.i)this.j&&c.charAt(0)!="/"&&a.push("/"),a.push(P(c,c.charAt(0)=="/"?Tb:Ub,!0));(c=this.g.toString())&&a.push("?",c);(c=this.u)&&a.push("#",P(c,Vb));return a.join("")};
M.prototype.resolve=function(a){var b=new M(this),c=!!a.m;c?Ob(b,a.m):c=!!a.v;c?b.v=a.v:c=!!a.j;c?b.j=a.j:c=a.A!=null;var d=a.i;if(c)Pb(b,a.A);else if(c=!!a.i){if(d.charAt(0)!="/")if(this.j&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");e!=-1&&(d=b.i.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],h=0;h<e.length;){var g=e[h++];g=="."?d&&h==e.length&&f.push(""):g==".."?((f.length>1||f.length==1&&f[0]!=
"")&&f.pop(),d&&h==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?b.i=d:c=a.g.toString()!=="";c?Qb(b,Rb(a.g)):c=!!a.u;c&&(b.u=a.u);return b};
var Ob=function(a,b,c){a.m=c?N(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))},Pb=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.A=b}else a.A=null},Qb=function(a,b,c){b instanceof O?(a.g=b,Wb(a.g,a.o)):(c||(b=P(b,Xb)),a.g=new O(b,a.o))},N=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},P=function(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Yb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Yb=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Sb=/[#\/\?@]/g,Ub=/[#\?:]/g,Tb=/[#\?]/g,Xb=/[#\?@]/g,Vb=/#/g,O=function(a,b){this.i=this.g=null;this.j=a||null;this.m=!!b},Q=function(a){a.g||(a.g=new Map,a.i=0,a.j&&xb(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};O.prototype.add=function(a,b){Q(this);this.j=null;a=R(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i+=1;return this};
var Zb=function(a,b){Q(a);b=R(a,b);a.g.has(b)&&(a.j=null,a.i-=a.g.get(b).length,a.g.delete(b))},$b=function(a,b){Q(a);b=R(a,b);return a.g.has(b)};O.prototype.forEach=function(a,b){Q(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var ac=function(a,b){Q(a);var c=[];if(typeof b==="string")$b(a,b)&&(c=c.concat(a.g.get(R(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
O.prototype.set=function(a,b){Q(this);this.j=null;a=R(this,a);$b(this,a)&&(this.i-=this.g.get(a).length);this.g.set(a,[b]);this.i+=1;return this};O.prototype.get=function(a,b){if(!a)return b;a=ac(this,a);return a.length>0?String(a[0]):b};
O.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=ac(this,d);for(var f=0;f<d.length;f++){var h=e;d[f]!==""&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.j=a.join("&")};
var Rb=function(a){var b=new O;b.j=a.j;a.g&&(b.g=new Map(a.g),b.i=a.i);return b},R=function(a,b){b=String(b);a.m&&(b=b.toLowerCase());return b},Wb=function(a,b){b&&!a.m&&(Q(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Zb(this,d),Zb(this,e),c.length>0&&(this.j=null,this.g.set(R(this,e),sa(c)),this.i+=c.length))},a));a.m=b};var bc=fa(["//imasdk.googleapis.com/js/sdkloader/ima3.js"]),cc=/Android|iPhone|iPod/i,dc={qa:function(a){return Ra(function(b){return b.body&&b.body.id==="HeavyAdIntervention"},a)}},S=function(){this.height=this.width=0;this.J=!1;this.m=this.K=this.F=this.H=null;this.D={};this.j={};this.C=null;this.L=this.O=this.N=!1;this.u=ec();var a=Object.values(Sa);a=r(a);for(var b=a.next();!b.done;b=a.next())this.D[b.value]=[];this.I=new Lb},fc,hc;
S.prototype.listen=function(a,b,c){this.j[b]=c.bind(this);a.addEventListener?a.addEventListener(b,this.j[b]):a.attachEvent(b,this.j[b])};
var T=function(a,b,c){a.j[c]&&(b.removeEventListener?b.removeEventListener(c,a.j[c]):b.detachEvent&&b.detachEvent(c,a.j[c]),delete a.j[c])},ec=function(){for(var a=u.document,b=RegExp("//imasdk.googleapis.com/js/sdkloader/vpaid_adapter[_a-z]*.js(\\?.*)?$"),c=null,d=0;d<a.scripts.length;d++)if(b.test(a.scripts[d].src)){c=a.scripts[d];break}if(c==null)return null;a=new M(c.src,!0);b=a.g.get("adTagUrl");if(!b||b.indexOf("http")!==0&&b.indexOf("//")!==0)return null;b=new M(b,!0);c=b.g.get("channel");
d="vpaidadp_html5";c&&(d=c+"+"+d);b.g.set("channel",d);(c=a.g.get("correlator"))&&(ic=+c||-1);(c=a.g.get("scor"))&&(jc=+c||-1);c=a.g.get("vpa");if(c==="1"||c==="0")fc=c==="1";c=a.g.get("vpmute");if(c==="1"||c==="0")hc=c==="1";kc(a,b);return b},kc=function(a,b){b.m==="https"&&["rdid","is_lat","idtype"].forEach(function(c){var d=a.g.get(c);d&&b.g.set(c,d)})},V=function(a,b,c){b=b===void 0?"Error":b;if(c){var d=c.toString();c.name&&d.indexOf(c.name)==-1&&(d+=": "+c.name);c.message&&d.indexOf(c.message)==
-1&&(d+=": "+c.message);if(c.stack)a:{c=c.stack;var e=d;try{c.indexOf(e)==-1&&(c=e+"\n"+c);for(var f;c!=f;)f=c,c=c.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");d=c.replace(RegExp("\n *","g"),"\n");break a}catch(h){d=e;break a}d=void 0}b+=": "+d}a.L=!0;U(a,b);lc(a)},mc=function(a){if(a.O&&a.I.g===0&&a.H&&a.F&&(a.u||a.m)){a.v=Qa("DIV",{style:"position: absolute; z-index: 99; width: 100%; height: 100%"});var b;(b=a.H)==null||b.insertBefore(a.v,a.H.firstChild);a.A=new google.ima.AdDisplayContainer(a.v,
a.F);a.A.initialize();a.o=new google.ima.AdsLoader(a.A);b=new google.ima.AdsRequest;var c=fc;c!=null&&b.setAdWillAutoPlay(c);c=hc;c!=null&&b.setAdWillPlayMuted(c);a.u?(b.adTagUrl=a.u.toString(),b.linearAdSlotHeight=a.height,b.linearAdSlotWidth=a.width,b.nonLinearAdSlotHeight=a.height,b.nonLinearAdSlotWidth=a.width):b.adsResponse=a.m;a.listen(a.o,google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,a.la);a.listen(a.o,google.ima.AdErrorEvent.Type.AD_ERROR,a.U);a.o.requestAds(b)}};m=S.prototype;
m.ha=function(){this.I.g===2?(this.L=!0,this.i("AdError")):mc(this)};m.ia=function(){return"2.0"};
m.ja=function(a,b,c,d,e,f){this.width=a;this.height=b;a=f&&f.slot;f=f&&f.videoSlot;if(e=(e=e&&e.AdParameters)?e.indexOf("&")!=-1?"document"in u?Fa(e):Ga(e):e:null)this.m=e;nc(this);a&&f&&(this.u||this.m)?(Nb(this.I,this.m,this.ha.bind(this)),this.H=a,this.F=f,cc.test(u.navigator.userAgent)&&this.F.load(),mc(this)):V(this,"Error during init:"+(a?"":" ad slot is missing")+(f?"":" video slot is missing")+(this.u||this.m?"":" no ad VAST or URL found"))};
m.va=function(){if(W(this))try{var a;(a=this.g)==null||a.init(this.width,this.height);var b;(b=this.g)==null||b.start()}catch(c){V(this,"",c)}else U(this)};m.wa=function(){if(this.N)oc(this);else if(W(this)){var a;(a=this.g)==null||a.stop()}else U(this)};m.pa=function(){if(W(this)){var a;(a=this.g)==null||a.pause()}else U(this)};m.sa=function(){if(W(this)){var a;(a=this.g)==null||a.resume()}else U(this)};
m.ra=function(a,b){if(W(this)){this.width=a;this.height=b;var c;(c=this.g)==null||c.resize(this.width,this.height);this.i("AdSizeChange")}else U(this)};m.X=function(){if(W(this)){var a;(a=this.g)==null||a.expand();this.J=!0;this.i("AdExpandedChange")}else U(this)};m.W=function(){if(W(this)){var a;(a=this.g)==null||a.collapse();this.J=!1;this.i("AdExpandedChange")}else U(this)};m.ua=function(){if(W(this)){var a;if((a=this.g)!=null&&a.getAdSkippableState()){var b;(b=this.g)==null||b.skip()}}else U(this)};
m.subscribe=function(a,b,c){(b=this.D[b])&&b.push({handler:a,scope:c})};m.V=function(a,b){var c=this.D[b],d=[];c&&(c.forEach(function(e){e.handler!==a&&d.push(e)}),this.D[b]=d)};m.da=function(){return!0};m.ga=function(){return this.width};m.ba=function(){return this.height};m.aa=function(){return this.J};m.getAdSkippableState=function(){if(!this.g)return!1;var a;return(a=this.g)==null?void 0:a.getAdSkippableState()};m.ea=function(){var a=-2;this.g&&(a=this.g.getRemainingTime(),a===-1&&(a=-2));return a};
m.Z=function(){return this.K?this.K.getDuration():-2};m.fa=function(){if(!this.g)return-1;var a;return(a=this.g)==null?void 0:a.getVolume()};m.ta=function(a){if(this.g){var b;(b=this.g)==null||b.setVolume(a)}};m.Y=function(){return""};m.ca=function(){return!1};
var W=function(a){return!a.L&&a.g!=null},lc=function(a){a.g&&(a.g.destroy(),T(a,a.g,google.ima.AdEvent.Type.IMPRESSION),T(a,a.g,google.ima.AdEvent.Type.STARTED),T(a,a.g,google.ima.AdEvent.Type.CLICK),T(a,a.g,google.ima.AdEvent.Type.FIRST_QUARTILE),T(a,a.g,google.ima.AdEvent.Type.MIDPOINT),T(a,a.g,google.ima.AdEvent.Type.THIRD_QUARTILE),T(a,a.g,google.ima.AdEvent.Type.COMPLETE),T(a,a.g,google.ima.AdEvent.Type.PAUSED),T(a,a.g,google.ima.AdEvent.Type.RESUMED),T(a,a.g,google.ima.AdEvent.Type.SKIPPED),
T(a,a.g,google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED),T(a,a.g,google.ima.AdEvent.Type.VOLUME_CHANGED),T(a,a.g,google.ima.AdEvent.Type.VOLUME_MUTED),T(a,a.g,google.ima.AdEvent.Type.USER_CLOSE),T(a,a.g,google.ima.AdEvent.Type.LOADED),T(a,a.g,google.ima.AdEvent.Type.LOG),T(a,a.g,google.ima.AdEvent.Type.ALL_ADS_COMPLETED),T(a,a.g,google.ima.AdErrorEvent.Type.AD_ERROR),delete a.g);a.o&&(a.o.destroy(),delete a.o);a.A&&(a.A.destroy(),delete a.A);if(a.v){var b=a.v;b&&b.parentNode&&b.parentNode.removeChild(b);
delete a.v}};S.prototype.i=function(a,b){(a=this.D[a])&&a.forEach(function(c){c.handler.apply(c.scope,b)})};var U=function(a,b){a.i("AdError",b?[b]:void 0)},pc=function(a){a.C==null&&(a.C=u.setInterval(S.prototype.i.bind(a,"AdRemainingTimeChange"),500))},qc=function(a){a.C!=null&&(u.clearInterval(a.C),a.C=null)};m=S.prototype;
m.na=function(a){this.O=!0;a.target!=null&&(T(this,a.target,"load"),T(this,a.target,"error"));google.ima.settings.setVpaidMode(google.ima.ImaSdkSettings.VpaidMode.INSECURE);google.ima.settings.setIsVpaidAdapter(!0);ic>0&&google.ima.settings.setPageCorrelator(ic);jc>0&&google.ima.settings.setStreamCorrelator(jc);mc(this)};m.oa=function(a){a.target&&(T(this,a.target,"load"),T(this,a.target,"error"));V(this,"SdkLoadError")};
m.la=function(a){this.g=a.getAdsManager(this.F);this.listen(this.g,google.ima.AdEvent.Type.IMPRESSION,this.B);this.listen(this.g,google.ima.AdEvent.Type.STARTED,this.B);this.listen(this.g,google.ima.AdEvent.Type.CLICK,this.B);this.listen(this.g,google.ima.AdEvent.Type.FIRST_QUARTILE,this.B);this.listen(this.g,google.ima.AdEvent.Type.MIDPOINT,this.B);this.listen(this.g,google.ima.AdEvent.Type.THIRD_QUARTILE,this.B);this.listen(this.g,google.ima.AdEvent.Type.COMPLETE,this.B);this.listen(this.g,google.ima.AdEvent.Type.PAUSED,
this.B);this.listen(this.g,google.ima.AdEvent.Type.RESUMED,this.B);this.listen(this.g,google.ima.AdEvent.Type.SKIPPED,this.B);this.listen(this.g,google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED,this.B);this.listen(this.g,google.ima.AdEvent.Type.VOLUME_CHANGED,this.B);this.listen(this.g,google.ima.AdEvent.Type.VOLUME_MUTED,this.B);this.listen(this.g,google.ima.AdEvent.Type.USER_CLOSE,this.B);this.listen(this.g,google.ima.AdEvent.Type.LOADED,this.ka);this.listen(this.g,google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
this.ma);this.listen(this.g,google.ima.AdErrorEvent.Type.AD_ERROR,this.U);this.i("AdLoaded")};
m.B=function(a){switch(a.type){case google.ima.AdEvent.Type.IMPRESSION:this.i("AdImpression");break;case google.ima.AdEvent.Type.STARTED:this.i("AdStarted");this.i("AdVideoStart");pc(this);break;case google.ima.AdEvent.Type.CLICK:this.i("AdClickThru",["","",!1]);break;case google.ima.AdEvent.Type.FIRST_QUARTILE:this.i("AdVideoFirstQuartile");break;case google.ima.AdEvent.Type.MIDPOINT:this.i("AdVideoMidpoint");break;case google.ima.AdEvent.Type.THIRD_QUARTILE:this.i("AdVideoThirdQuartile");break;
case google.ima.AdEvent.Type.COMPLETE:this.i("AdVideoComplete");break;case google.ima.AdEvent.Type.PAUSED:this.i("AdPaused");qc(this);break;case google.ima.AdEvent.Type.RESUMED:this.i("AdPlaying");pc(this);break;case google.ima.AdEvent.Type.SKIPPED:this.i("AdSkipped");qc(this);break;case google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED:this.i("AdSkippableStateChange");break;case google.ima.AdEvent.Type.VOLUME_CHANGED:case google.ima.AdEvent.Type.VOLUME_MUTED:this.i("AdVolumeChange");break;case google.ima.AdEvent.Type.USER_CLOSE:this.i("AdUserClose")}};
m.ka=function(a){this.K=a.getAd()};m.U=function(a){a=a.getError?a.getError():null;var b="AdError"+(a?" "+a.getErrorCode()+" ("+a.getMessage()+")":"");V(this,b,a)};m.ma=function(){this.N=!0;qc(this);oc(this)};var oc=function(a){u.setTimeout(function(){lc(a);a.i("AdStopped")},100)},nc=function(a){dc.qa(function(b){a.i("AdError",["HeavyAdIntervention: "+b.body.message])})},rc=function(){var a="T";S.T&&S.hasOwnProperty(a)?a=S.T:(a=new S,S.T=a);return a},ic=-1,jc=-1;var X=rc(),sc=function(a){var b=ha.apply(1,arguments);if(b.length===0)return Aa(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Aa(c)}(bc),Y=Qa("SCRIPT");Y.type="text/javascript";var tc;if(sc instanceof za)tc=sc.g;else throw Error("");Y.src=tc;var uc,Z=Y.ownerDocument;Z=Z===void 0?document:Z;var vc,wc,xc=(wc=(vc=Z).querySelector)==null?void 0:wc.call(vc,"script[nonce]");(uc=xc==null?"":xc.nonce||xc.getAttribute("nonce")||"")&&Y.setAttribute("nonce",uc);
X.listen(Y,"load",X.na);X.listen(Y,"error",X.oa);var yc=u.document;(yc.body||yc.head).appendChild(Y);S.prototype.handshakeVersion=S.prototype.ia;S.prototype.initAd=S.prototype.ja;S.prototype.resizeAd=S.prototype.ra;S.prototype.startAd=S.prototype.va;S.prototype.stopAd=S.prototype.wa;S.prototype.pauseAd=S.prototype.pa;S.prototype.resumeAd=S.prototype.sa;S.prototype.expandAd=S.prototype.X;S.prototype.collapseAd=S.prototype.W;S.prototype.skipAd=S.prototype.ua;S.prototype.subscribe=S.prototype.subscribe;
S.prototype.unsubscribe=S.prototype.V;S.prototype.getAdLinear=S.prototype.da;S.prototype.getAdWidth=S.prototype.ga;S.prototype.getAdHeight=S.prototype.ba;S.prototype.getAdExpanded=S.prototype.aa;S.prototype.getAdSkippableState=S.prototype.getAdSkippableState;S.prototype.getAdRemainingTime=S.prototype.ea;S.prototype.getAdDuration=S.prototype.Z;S.prototype.getAdVolume=S.prototype.fa;S.prototype.setAdVolume=S.prototype.ta;S.prototype.getAdCompanions=S.prototype.Y;S.prototype.getAdIcons=S.prototype.ca;
u.getVPAIDAd=function(){return rc()};}).call(this);
